
[font]
size = 17

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[terminal]

[terminal.shell]
program = "tmux"


[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/gruvbox-dark.toml"]
