
window.opacity = 0.9

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[terminal]

[terminal.shell]
program = "/bin/bash"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\x1b\r"

[general]
live_config_reload = true
import = [
	"~/.config/alacritty/themes/themes/gruvbox-dark.toml"
]
