#################################################
#               auto start apps                 #
#################################################

# Disable automatic lock/idle (system-wide 90-swayidle.conf)
exec pkill swayidle

# enable clipboard manager
exec wl-paste --watch cliphist store

# enable auto tiling
exec_always autotiling -l 2

