#################################################
#               auto start apps                 #
#################################################

# Disable automatic lock/idle (system-wide 90-swayidle.conf)
exec pkill swayidle

# enable clipboard manager
exec wl-paste --watch cliphist store

# enable auto tiling
exec_always autotiling -l 2

# Workspace 1: Terminal
#exec swaymsg "workspace 1; exec ghostty"

# Teams is auto-assigned fullscreen to workspace 4
