######################################################################
#        ______          __     ____                 __  ______      #
#       / ____/___  ____/ /__  / __ \____  _____    / / / / __ \     #
#      / /   / __ \/ __  / _ \/ / / / __ \/ ___/   / /_/ / / / /     #
#     / /___/ /_/ / /_/ /  __/ /_/ / /_/ (__  )   / __  / /_/ /      #
#     \____/\____/\__,_/\___/\____/ .___/____/   /_/ /_/\___\_\      #
#                                /_/                                 #
######################################################################

#################################################
#                Output configuration           #
#################################################

# Built-in laptop display (1920x1080 @ 60Hz)
output eDP-1 {
    resolution 1920x1080@60.052Hz
    position 0,0
    max_render_time 15
    adaptive_sync off
}

# External monitor — LG UltraGear 2560x1440
output DP-4 {
    resolution 2560x1440@59.951Hz
    position 0,0
    max_render_time 15
    adaptive_sync off
}
# Active canvas (Main Monitor)
workspace 1 output DP-4
workspace 2 output DP-4
workspace 3 output DP-4
workspace 4 output DP-4

# Static dashboard (14-inch bottom monitor)
workspace 5 output DP-1
workspace 6 output DP-1
workspace 7 output DP-1
